#ifndef JITTER_SCENARIO_2_H
#define JITTER_SCENARIO_2_H

#include "scenario.h"

/* APER TASK PARAMS */
#define APER_TASK_1_PRIORITY_SCENARIO_2         1
#define APER_TASK_REST_PRIORITY_SCENARIO_2      0

/* PERIODIC TASK */
#define PERIODIC_TASK_PRIORITY_SCENARIO_2       2

/* NEED TO ENABLE TIME SLICING IN ZEPHYR*/

void startJitterTestScenario_2()
{
    startJitterTestScenario(APER_TASK_1_PRIORITY_SCENARIO_2, APER_TASK_REST_PRIORITY_SCENARIO_2, PERIODIC_TASK_PRIORITY_SCENARIO_2, "scenario_2");
}

#endif // JITTER_SCENARIO_2_H
