#ifndef JITTER_SCENARIO_1_H
#define JITTER_SCENARIO_1_H

#include "scenario.h"

/* APER TASK PARAMS */
#define APER_TASK_1_PRIORITY_SCENARIO_1         0
#define APER_TASK_REST_PRIORITY_SCENARIO_1      0

/* PERIODIC TASK */
#define PERIODIC_TASK_PRIORITY_SCENARIO_1       0

/* NEED TO ENABLE TIME SLICING IN ZEPHYR*/

void startJitterTestScenario_1()
{
    startJitterTestScenario(APER_TASK_1_PRIORITY_SCENARIO_1, APER_TASK_REST_PRIORITY_SCENARIO_1, PERIODIC_TASK_PRIORITY_SCENARIO_1, "scenario_1");
}


#endif // JITTER_SCENARIO_1_H
