#ifndef JITTER_SCENARIO_3_H
#define JITTER_SCENARIO_3_H

#include "scenario.h"

/* APER TASK PARAMS */
#define APER_TASK_1_PRIORITY_SCENARIO_3         0
#define APER_TASK_REST_PRIORITY_SCENARIO_3      0

/* PERIODIC TASK */
#define PERIODIC_TASK_PRIORITY_SCENARIO_3       1

/* NEED TO ENABLE TIME SLICING IN ZEPHYR*/

void startJitterTestScenario_3()
{
    addSecondPeriodicTask(PERIODIC_TASK_PRIORITY_SCENARIO_3);
    startJitterTestScenario(APER_TASK_1_PRIORITY_SCENARIO_3, APER_TASK_REST_PRIORITY_SCENARIO_3, PERIODIC_TASK_PRIORITY_SCENARIO_3, "scenario_3");
}

#endif // JITTER_SCENARIO_3_H
